language: go
go:
  - 1.13

script:
  - env GOOS=linux GOARCH=amd64 go build -o build/linux/agent_linux_amd64 .
  - env GOOS=darwin GOARCH=amd64 go build -o build/linux/agent_darvin_amd64 .

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - build/linux/agent_linux_amd64
    - build/linux/agent_darwin_amd64
  skip_cleanup: true
  on:
    tags: true